### ISSUE TITLE
Phân loại người dùng

### ISSUE THREAD

**Issue by MyHau-team5** [MyHau-team5/group5_id17#18]
Tạo hình các actors trong hệ thống 
Mẫu: Xem document của thầy mục II.2.

**Comment by HieuShin7703** [comment]
<img width="574" alt="Image" src="https://github.com/user-attachments/assets/eb791d09-cdc1-4182-a88b-bf7817c8ee0e" />

**Comment by HieuShin7703** [comment]
![Image](https://github.com/user-attachments/assets/8f9ebb71-241a-41b5-b207-aafdea170d9c)

**Comment by HieuShin7703** [comment]
Mô hình Use Case Diagram ( mô tả các tương tác giữa các actor và hệ thống ) :
![Image](https://github.com/user-attachments/assets/a401e01e-a351-444a-94cb-e98994e1f3ee)
