### ISSUE TITLE
Môi trường thiết kế và xây dựng

### ISSUE THREAD

**Issue by MyHau-team5** [MyHau-team5/group5_id17#19]
Xem mục: II.3. Môi trường thiết kế & xây dựng

**Comment by khoivancw** [comment]
II.3. Môi Trường Thiết Kế & Xây Dựng 

Website nền tảng đặt lịch cho phòng khám nha khoa được xây dựng trên công nghệ Django với các yêu cầu cụ thể như sau: 

Công Nghệ Phát Triển: 

Sử dụng Django (phiên bản mới nhất) để phát triển ứng dụng web. 

Ngôn Ngữ Lập Trình: 

Sử dụng Python làm ngôn ngữ lập trình chính cho dự án. 

Cơ Sở Dữ Liệu: 

Sử dụng SQL Server (phiên bản 2022) để quản lý và lưu trữ dữ liệu. 

Quản Lý Mã Nguồn: 

Sử dụng Git để quản lý mã nguồn và GitHub để lưu trữ và chia sẻ dự án. 

Tương Thích Trình Duyệt: 

Đảm bảo hoạt động tốt trên các trình duyệt phổ biến như: 

Google Chrome 

Mozilla Firefox 

Safari 

Internet Explorer 

Tương Thích Thiết Bị: 

Đảm bảo hoạt động tốt trên nhiều loại thiết bị khác nhau, bao gồm: 

Máy tính để bàn (Computer) 

Điện thoại thông minh (Smartphone) 

Máy tính bảng (iPad)
