### ISSUE TITLE
Tổng hợp tất cả các nội dung mà nhóm đã tìm được

### ISSUE THREAD

**Issue by MyHau-team5** [MyHau-team5/group5_id17#20]
Tổng hợp phần nội dung mà nhóm đã tìm hiểu được làm 1 file 
Yêu cầu file:
- Các mục phân chia phải hợp lý 
- Theo thứ tự và dễ nhìn

**Comment by huyhandsome77** [comment]
[TỔNG HỢP.docx](https://github.com/user-attachments/files/18185552/T.NG.H.P.docx)
