### ISSUE TITLE
class guest + use case customer

### ISSUE THREAD

**Issue by MyHau-team5** [MyHau-team5/group5_id17#23]

**Comment by Hazuu58** [comment]
> Class: Guest

> Attributes:
        IP
> Behaviors:
	Xem danh sách các dịch vụ mới cập nhật
        Xem danh sách dịch vụ theo từng danh mục
        Xem thông tin về phòng khám: Điện thoại, Fax, Địa chỉ và các thông tin giới thiệu khác.
        Xem chi tiết dịch vụ , và các dịch vụ cùng danh mục.
        Xem danh sách các dịch vụ HOT nhất (có số lượng lựa chọn nhiều nhất)
        Tìm kiếm dịch vụ nâng cao (dựa vào khoảng giá và trình độ nha sĩ )
        Lọc trên kết quả tìm kiếm theo: danh mục hoặc tên nha sĩ
        Tạo tài khoản để tư vấn và đặt lịch
        Tìm kiếm dịch vụ theo tên
