### ISSUE TITLE
class employee + use guest

### ISSUE THREAD

**Issue by MyHau-team5** [MyHau-team5/group5_id17#24]

**Comment by Lethanh05** [comment]
class: employee
Attributes:
- id: int
- fullname: String
- phone: String
- gender: boolean
- email: String
- salary: Double
- address: String
- role: list <Role>
+ displayInfor(): void

**Comment by Lethanh05** [comment]
<img width="263" alt="Image" src="https://github.com/user-attachments/assets/9bf5db35-e7c5-4b98-bfc1-22e379b45df5" />

bổ sung thêm use case guest:
đăng nhập
tư vấn online ( qua chatbox)
