### ISSUE TITLE
class dentist + use case  guest

### ISSUE THREAD

**Issue by MyHau-team5** [MyHau-team5/group5_id17#25]

**Comment by huyhandsome77** [comment]
**Class :** Dentist

**Attributes:**
+ Id : int
+ FullName : string 
+ Birthday : date
+ Gender : boolean
+ Email : string
+ Phone : string
+ Address : string
- License_number : string
+ Exp_years : int
+ Specialization : string
+ Image : string

![Image](https://github.com/user-attachments/assets/2570b3a7-07e1-4fe2-a10e-f8764e3adaad)
