### ISSUE TITLE
class admin + class clinic owner + use case admin

### ISSUE THREAD

**Issue by MyHau-team5** [MyHau-team5/group5_id17#27]

**Comment by khoivancw** [comment]
Class : Admin

Attributes:
- Id : int
- FullName : string
- Email : string
- Phone : string
- Role : string
- CreatedAt : date
Class : ClinicOwner

Attributes:
- Id : int
- FullName : string
- Email : string
- Phone : string
- ClinicName : string
- LicenseNumber : string
- Address : string
- EstablishedYear : int

**Comment by khoivancw** [comment]
<img width="205" alt="Image" src="https://github.com/user-attachments/assets/49c86136-5968-44db-8975-5dbf61643892" />
